const mongoose = require("mongoose");
const { Schema, model } = mongoose;

const LicenseSchema = new Schema(
  {
    // ── Key (generated by Open LLM + HMAC signed) ─
    license_key: { type: String, required: true, unique: true },
    license_code: { type: String, required: true, unique: true },

    // ── Per-seat credentials ───────────────────────
    // user_id: e.g. ABCLI-U1, ABCLI-U2 (login username for this seat)
    user_id: { type: String },
    // seat_password: bcrypt hash of plain password (e.g. ABCLI1) — shown ONCE in API response
    seat_password: { type: String },

    // ── Ownership ──────────────────────────────────
    key_index: { type: Number, default: 1 },
    institute_id: { type: Schema.Types.ObjectId, ref: "Institute", required: true },
    purchased_by: {
      type: Schema.Types.ObjectId,
      ref: "SuperAdmin",
      required: true,
    },
    // ✅ FIXED: was purchase_by (typo) → purchased_by

    // ── Seats ──────────────────────────────────────
    // ✅ FIXED: was total_license with max:5 hardcoded
    // ✅ FIXED: removed student_id[], is_assigned, assigned_at
    total_seats: { type: Number, required: true, default: 5 },
    // no max cap — can be 5, 19, 50, 100, any number

    // ✅ ADDED: live counter — inc on login, dec on logout
    active_sessions: { type: Number, default: 0 },

    // ── Validity ───────────────────────────────────
    start_date: { type: Date, required: true },
    expiry_date: { type: Date, required: true },
    duration: { type: Number, required: true }, // days e.g. 365

    // ── Status ─────────────────────────────────────
    status: {
      type: String,
      enum: ["active", "expired", "revoked", "suspended"],
      default: "active",
    },

    // ── Open LLM metadata ──────────────────────────
    llm_metadata: {
      model_used: { type: String },
      llm_used: { type: Boolean },
      time_ms: { type: Number },
      key_pattern: { type: String },
      signature: { type: String },
    },
  },
  { timestamps: true, toJSON: { virtuals: true }, toObject: { virtuals: true } },
);

// ✅ FIXED: was this.valid_until (field doesn't exist!) → this.expiry_date
LicenseSchema.virtual("is_valid").get(function () {
  return this.status === "active" && new Date() <= this.expiry_date;
});

// ✅ ADDED: check if seat is free before login
LicenseSchema.virtual("has_free_seat").get(function () {
  return this.active_sessions < this.total_seats;
});

// ✅ FIXED: was this.valid_until → this.expiry_date
LicenseSchema.virtual("days_remaining").get(function () {
  return Math.max(0, Math.ceil((this.expiry_date - new Date()) / 86400000));
});

LicenseSchema.index({ institute_id: 1, status: 1 });

module.exports = model("License", LicenseSchema);
